# Generated by Django 3.1 on 2022-10-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Terminado', 'Terminado')], default='Pendiente', max_length=20)),
                ('fecha_inicio', models.DateField(auto_now=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
