# Generated by Django 3.1 on 2022-10-20 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitud', '0001_initial'),
        ('tarea', '0001_initial'),
        ('orden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orden_trabajo', to='solicitud.solicitud'),
        ),
        migrations.AddField(
            model_name='orden',
            name='tareas',
            field=models.ManyToManyField(through='orden.TareaOrden', to='tarea.Tarea'),
        ),
    ]
