# Generated by Django 3.1 on 2022-10-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orden', '0002_auto_20221020_0015'),
        ('trabajador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='trabajadores',
            field=models.ManyToManyField(to='trabajador.Trabajador'),
        ),
    ]
