# Generated by Django 3.1 on 2022-10-19 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Cancelada', 'Cancelada'), ('Completado', 'Completado')], default='Pendiente', max_length=20)),
                ('fecha', models.DateField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='cliente.cliente')),
                ('equipos', models.ManyToManyField(to='cliente.Equipo')),
            ],
        ),
    ]
