# Generated by Django 3.1 on 2022-10-19 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitud', '0001_initial'),
        ('trabajador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='jefe_equipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_jefe_equipo', to='trabajador.trabajador'),
        ),
    ]
