# Generated by Django 3.1 on 2022-10-19 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trabajador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajador_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
